version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
    # env_file:
    #   - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '4200:4200'
    command: ng serve --host 0.0.0.0 --poll 200